// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Delete(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function DetectADB():Promise<string>;

export function ListDebugPackages(arg1:string):Promise<Array<main.DebugPackage>>;

export function ListDevices():Promise<Array<main.Device>>;

export function ListPackageDirectory(arg1:string,arg2:string,arg3:string):Promise<Array<main.DirectoryEntry>>;

export function ListWifiPairingDevices():Promise<Array<main.WifiPairingDevice>>;

export function PackageContext(arg1:string):Promise<string>;

export function PairAndConnect(arg1:string,arg2:string):Promise<string>;

export function PairWithCode(arg1:string,arg2:string):Promise<void>;

export function PreviewFile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.FilePreview>;

export function ReadFile(arg1:string,arg2:string,arg3:string):Promise<main.FileContent>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartWifiPairing():Promise<main.WifiPairingOffer>;

export function StopWifiPairing():Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function WifiPairingStatus():Promise<main.WifiPairingStatus>;
