// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Delete'](arg1, arg2, arg3, arg4);
}

export function DetectADB() {
  return window['go']['main']['App']['DetectADB']();
}

export function ListDebugPackages(arg1) {
  return window['go']['main']['App']['ListDebugPackages'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListPackageDirectory(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListPackageDirectory'](arg1, arg2, arg3);
}

export function PackageContext(arg1) {
  return window['go']['main']['App']['PackageContext'](arg1);
}

export function PreviewFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewFile'](arg1, arg2, arg3, arg4);
}

export function ReadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2, arg3);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3);
}

export function UploadFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3, arg4, arg5);
}
